spring:
  config:
    activate:
      on-profile: prod

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true
