
POST localhost:8080/patients
Content-Type: application/json

{
  "id": "",
  "hospitalId": "1",
  "name": "헷",
  "sex": "M",
  "dateOfBirth" : "20120122",
  "phoneNo" : "01081621722"
}

###

#PUT localhost:8080/patients
#Content-Type: application/json
#
#{
#  "id": "102",
#  "hospitalId": "1",
#  "name": "안뇽",
#  "sex": "M",
#  "dateOfBirth" : "20120122",
#  "phoneNo" : "01081621722"
#}

###

#DELETE localhost:8080/patients/101
#Content-Type: application/json

###

#GET localhost:8080/patients/102
#Content-Type: application/json

GET localhost:8080/patients
Content-Type: application/json
